Repository vispy/vispy, pull requests merged in 2019-07, with the labels that each got.

#1654 Add pyproject.toml file for better build support
  pyproject.toml
  setup.py
Labels: build, type: fix

#1596 [MRG] Allow XYZAxisVisual override of position, color, connect, and method
  vispy/visuals/xyz_axis.py
Labels: component: visuals, type: enhancement

#1558 Add element-wise colors to TextVisual
  examples/basics/visuals/text_scatter.py
  vispy/visuals/text/text.py
Labels: component: visuals, type: enhancement, type: feature

#1567 Add WindbarbVisual
  examples/basics/visuals/windbarb_quiver.py
  vispy/scene/visuals.py
  vispy/testing/image_tester.py
  vispy/visuals/__init__.py
  vispy/visuals/tests/test_windbarb.py
  vispy/visuals/windbarb.py
Labels: component: visuals, type: feature

#1595 Fix read_mesh of STL files
  vispy/io/mesh.py
Labels: component: io, type: fix

#1658 Add ability for multi-radii on TubeVisual
  examples/basics/visuals/tube.py
  vispy/visuals/tube.py
Labels: component: visuals, type: enhancement

#1660 Fix reading depth buffers with read_pixels
  vispy/gloo/framebuffer.py
  vispy/gloo/tests/test_wrappers.py
  vispy/gloo/wrappers.py
Labels: type: fix

#1661 Fix AGG line artifacts from transparent colors
  vispy/glsl/lines/agg.vert
Labels: component: visuals, type: fix

#1637 [MRG] Offscreen EGL rendering code (replacement of #1464 and #1602)
  examples/offscreen/simple_egl.py
  vispy/app/backends/_egl.py
  vispy/ext/egl.py
  vispy/gloo/glir.py
Labels: type: fix

#1662 Fix numpy 1.17 deprecation warnings about dtype creation
  vispy/visuals/line/arrow.py
  vispy/visuals/line/line.py
Labels: type: fix

#1671 Fix primitive_mesh_viewer_qt.py and wiggly_bar.py examples
  examples/demo/gloo/primitive_mesh_viewer_qt.py
  examples/demo/visuals/wiggly_bar.py
Labels: type: fix

#1676 Fix transparency in molecular_viewer on some machines
  examples/demo/gloo/molecular_viewer.py
Labels: type: fix

#1677 Add automatic PyPI deployment through Azure
  MANIFEST.in
  azure-pipelines.yml
  setup.py
  vispy/__init__.py
Labels: build
