Repository vispy/vispy, pull requests merged in 2019-04, with the labels that each got.

#1621 Fix PySide2 qWait monkey patching
  vispy/app/backends/_pyside2.py
Labels: type: fix

#1628 Make sure segments have the right format
  vispy/geometry/triangulation.py
Labels: type: fix

#1632 Add 'python_requires' to setup.py
  .travis.yml
  setup.py
Labels: build

#1521 Switch examples from PyQt4 to PyQt5
  examples/basics/scene/modular_shaders/editor.py
  examples/basics/scene/modular_shaders/sandbox.py
  examples/benchmark/simple_vispy.py
  examples/demo/gloo/glsl_sandbox_cube.py
  examples/demo/gloo/primitive_mesh_viewer_qt.py
  examples/demo/gloo/two_qt_widgets.py
  examples/demo/visuals/wiggly_bar.py
  examples/tutorial/app/app_events.py
  examples/tutorial/app/shared_context.py
Labels: type: example
