Repository vispy/vispy, pull requests merged in 2019-11, with the labels that each got.

#1702 Fix MarkerVisual scaling when rotating in 3D space
  vispy/visuals/markers.py
Labels: type: enhancement

#1756 Fix shader version handling in webgl backend
  azure-pipelines.yml
  setup.py
  vispy/gloo/glir.py
  vispy/gloo/tests/test_glir.py
Labels: type: bug

#1758 Fix texture alignment to use data itemsize
  vispy/gloo/glir.py
  vispy/gloo/tests/test_glir.py
  vispy/gloo/texture.py
Labels: type: bug

#1749 mesh bounds index error
  vispy/visuals/mesh.py
  vispy/visuals/tests/test_mesh.py
Labels: component: scene, type: bug

#1557 Fixed a bug in linking two flycameras
  vispy/scene/cameras/fly.py
Labels: type: bug

#1743 Bug fixes related to AxisVisual
  vispy/visuals/axis.py
  vispy/visuals/tests/test_axis.py
  vispy/visuals/tests/test_text.py
  vispy/visuals/text/text.py
Labels: component: visuals, type: bug

#1744 Improve AxisVisual visual by providing property getters and setters
  vispy/visuals/axis.py
Labels: component: visuals, type: enhancement

#1766 Fix additional numpy warnings when dealing with dtypes of size 1
  vispy/visuals/collections/collection.py
Labels: code-quality

#1748 Fix xaxis labels being wrong initially in PlotWidget
  vispy/plot/plotwidget.py
  vispy/plot/tests/test_plot.py
Labels: component: plot, type: bug

#1768 Fix string formatting of array shape
  vispy/visuals/transforms/_util.py
Labels: type: bug
