Repository vispy/vispy, pull requests merged in 2020-09, with the labels that each got.

#1908 Fix test runners not passing arguments properly on Windows
  README.rst
  azure-pipelines.yml
  vispy/testing/_runners.py
Labels: build

#1842 Implement volume contrast limits in shader, add gamma
  vispy/visuals/tests/test_volume.py
  vispy/visuals/volume.py
Labels: component: visuals, type: enhancement

#1911 Fix ImageVisual not updating color transform after texture update
  vispy/visuals/image.py
Labels: component: visuals, type: bug

#1913 Fix various numpy deprecation warnings
  azure-pipelines.yml
  vispy/io/datasets.py
  vispy/io/image.py
  vispy/io/tests/test_io.py
Labels: code-quality

#1914 Fix ImportError on Python 3.9
  vispy/geometry/torusknot.py
Labels: code-quality, type: bug

#1886 Let camera link be limited to specified properties
  vispy/geometry/rect.py
  vispy/scene/cameras/base_camera.py
  vispy/scene/cameras/tests/test_link.py
Labels: component: scene, type: enhancement

#1883 Fix OpenGL to ctypes type mapping
  codegen/createglapi.py
  vispy/gloo/gl/_es2.py
  vispy/gloo/gl/_gl2.py
  vispy/gloo/gl/_pyopengl2.py
Labels: component: gl, type: bug

#1919 Use oldest-supported-numpy in pyproject.toml
  pyproject.toml
Labels: build
