Repository vispy/vispy, pull requests merged in 2020-10, with the labels that each got.

#1928 Remove bundled decorator dependency
  setup.cfg
  vispy/ext/_bundled/decorator.py
  vispy/ext/decorator.py
  vispy/visuals/transforms/_util.py
Labels: build, code-quality

#1930 Fix typo in examples/basics/gloo/hello_fbo.py
  examples/basics/gloo/hello_fbo.py
Labels: docs-website

#1933 Remove six dependency
  examples/basics/scene/colored_line.py
  examples/basics/scene/flipped_axis.py
  setup.cfg
  vispy/app/application.py
  vispy/app/backends/_ipynb_util.py
  vispy/app/backends/_ipynb_webgl.py
  vispy/app/backends/_qt.py
  vispy/app/canvas.py
  vispy/app/tests/test_app.py
  vispy/app/timer.py
  vispy/color/color_array.py
  vispy/color/color_space.py
  vispy/color/colormap.py
  vispy/ext/_bundled/png.py
  vispy/ext/_bundled/six.py
  vispy/ext/six.py
  vispy/geometry/calculations.py
  vispy/geometry/meshdata.py
  vispy/gloo/buffer.py
  vispy/gloo/framebuffer.py
  vispy/gloo/gl/tests/test_basics.py
  vispy/gloo/glir.py
  vispy/gloo/program.py
  vispy/gloo/texture.py
  vispy/gloo/util.py
  vispy/gloo/wrappers.py
  vispy/scene/widgets/console.py
  vispy/scene/widgets/viewbox.py
  vispy/testing/_testing.py
  vispy/testing/image_tester.py
  vispy/util/config.py
  vispy/util/event.py
  vispy/util/fetching.py
  vispy/util/keys.py
  vispy/util/logs.py
  vispy/visuals/graphs/graph.py
  vispy/visuals/histogram.py
  vispy/visuals/image.py
  vispy/visuals/line/line.py
  vispy/visuals/mesh.py
  vispy/visuals/shaders/expression.py
  vispy/visuals/shaders/function.py
  vispy/visuals/shaders/shader_object.py
  vispy/visuals/shaders/variable.py
  vispy/visuals/spectrogram.py
  vispy/visuals/text/text.py
Labels: code-quality

#1934 Replaced bundled 'pypng' (png) dependency with pillow
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  setup.py
  vispy/ext/_bundled/png.py
  vispy/ext/png.py
  vispy/io/image.py
Labels: code-quality, component: util

#1943 Removed Python 2.7 wrapper on GzipFile
  vispy/ext/gzip_open.py
  vispy/io/wavefront.py
Labels: code-quality
