Repository vispy/vispy, pull requests merged in 2021-02, with the labels that each got.

#1956 Modified data type in create_sphere()
  vispy/geometry/generation.py
  vispy/geometry/tests/test_generation.py
Labels: type: bug

#1975 Add workaround for MacOS dlopen
  vispy/ext/cocoapy.py
Labels: type: bug

#1449 Changed vispy.plot.Fig.__init__() to allow passing 'keys' argument
  vispy/plot/fig.py
Labels: component: plot, type: enhancement

#1480 Add new example for mouse editing/drawing of shapes
  examples/basics/scene/shape_draw.py
Labels: type: example

#1974 MNT: build wheels on GitHub Actions
  .github/workflows/wheels.yml
  azure-pipelines.yml
  vispy/util/fonts/tests/test_font.py
Labels: build
