Repository vispy/vispy, pull requests merged in 2021-11, with the labels that each got.

#2257 Use stacklevel in DeprecationWarnings.
  vispy/gloo/texture.py
  vispy/visuals/cube.py
  vispy/visuals/markers.py
Labels: code-quality

#2261 Clarified docstring for ArrowVisual
  vispy/visuals/line/arrow.py
Labels: code-quality, component: visuals

#2251 Add optional dependencies section to installation instructions
  doc/installation.rst
Labels: docs-website

#2245 Update clims in color transform whenever texture._data_limits changes
  ci/requirements/linux_osmesa_deps_conda.txt
  vispy/visuals/_scalable_textures.py
  vispy/visuals/image.py
  vispy/visuals/tests/test_image.py
Labels: type: bug

#2262 Fix MeshNormals and WireframeFilter with empty MeshData
  vispy/geometry/meshdata.py
  vispy/visuals/filters/mesh.py
  vispy/visuals/filters/tests/__init__.py
  vispy/visuals/filters/tests/test_wireframe_filter.py
  vispy/visuals/mesh_normals.py
  vispy/visuals/tests/test_mesh_normals.py
Labels: type: bug, component: visuals

#2264 Add typing to `create_visual_node`
  vispy/scene/visuals.py
Labels: code-quality
