Repository vispy/vispy, pull requests merged in 2024-05, with the labels that each got.

#2588 Fix integral computation in attenuated mip
  vispy/visuals/volume.py
Labels: type: bug, component: gl

#2592 Add extra for glfw
  setup.py
Labels: component: app, build

#2589 Clip step size based on maximum detail on an 8K monitor
  vispy/visuals/volume.py
Labels: component: visuals, type: performance
